# Generated by Django 5.1.4 on 2024-12-10 08:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('EmployeeApp', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='employees',
            old_name='EmployeeID',
            new_name='EmployeeId',
        ),
    ]
